# Generated by Django 5.1.5 on 2025-02-04 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0002_create_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'message',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to='web.message'
                    ),
                ),
            ],
        ),
    ]
