# Generated by Django 5.1.5 on 2025-02-07 09:32

from django.db import migrations


def create_scheduled_task(apps, schema_editor):
    Schedule = apps.get_model('django_q', 'Schedule')
    Schedule.objects.get_or_create(
        func='cron.tasks.process_pending_jobs',
        schedule_type='I',
        minutes=30,
        defaults={'name': 'Process Pending Jobs'},
    )


def delete_scheduled_task(apps, schema_editor):
    Schedule = apps.get_model('django_q', 'Schedule')
    Schedule.objects.filter(func='cron.tasks.process_pending_jobs').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cron', '0002_add_index_job'),
        ('django_q', '__latest__'),
    ]

    operations = [
        migrations.RunPython(
            code=create_scheduled_task, reverse_code=delete_scheduled_task
        ),
    ]
