# Generated by Django 5.1.5 on 2025-02-04 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('FINAL_WORD', 'Final Word'),
                            ('TIME_CAPSULE', 'Time Capsule'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'recipients',
                    models.TextField(
                        help_text='Comma-separated list of email recipients'
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('SCHEDULED', 'Scheduled'),
                            ('DELIVERED', 'Delivered'),
                        ],
                        max_length=20,
                    ),
                ),
                ('subject', models.CharField(max_length=255)),
                ('text', models.TextField()),
                (
                    'delay',
                    models.IntegerField(
                        blank=True,
                        help_text='Delay before sending message for FINAL_WORD (in days)',
                        null=True,
                    ),
                ),
                (
                    'scheduled_at',
                    models.DateTimeField(
                        blank=True,
                        help_text='When the message is scheduled to be sent for TIME_CAPSULE',
                        null=True,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='messages',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
