# Generated by Django 5.1.5 on 2025-02-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_create_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(
                choices=[('SCHEDULED', 'Scheduled'), ('DELIVERED', 'Delivered')],
                default='SCHEDULED',
                max_length=20,
            ),
        ),
    ]
