# Generated by Django 5.1.5 on 2025-02-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_add_default_status_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='type',
            field=models.CharField(
                choices=[
                    ('CHECKED_IN', 'Checked In'),
                    ('MESSAGE_CREATED', 'Message Created'),
                    ('MESSAGE_DELIVERED', 'Message Delivered'),
                    ('MESSAGE_DELETED', 'Message Deleted'),
                ],
                max_length=20,
            ),
        ),
    ]
