# Generated by Django 5.1.5 on 2025-02-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_add_type_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='delay',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text='Delay before sending message for FINAL_WORD (in days)',
                null=True,
            ),
        ),
    ]
