# Generated by Django 5.1.5 on 2025-02-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_update_delay_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(
                choices=[
                    ('SCHEDULED', 'Scheduled'),
                    ('DELIVERED', 'Delivered'),
                    ('FAILED', 'Failed'),
                ],
                default='SCHEDULED',
                max_length=20,
            ),
        ),
    ]
