# Generated by Django 5.1.5 on 2025-02-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_create_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interval',
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text='Interval after which user is considered inactive (in days)',
            ),
        ),
    ]
