# Generated by Django 5.1.6 on 2025-02-25 17:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_update_interval_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_checkin',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text='Last timestamp user checked in at',
            ),
            preserve_default=False,
        ),
    ]
